default_agent: aihypechecker
agents:
  aihypechecker:
    name: aihypechecker
    language: python
    node_version: '20'
    entrypoint: agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/yuukiyamashita/ai-hype-checker/agent
    aws:
      execution_role: arn:aws:iam::761018866498:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-36a50f870b
      execution_role_auto_create: false
      account: '761018866498'
      region: us-east-1
      ecr_repository: 761018866498.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aihypechecker
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: aihypechecker-pgOaAXEdR7
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:761018866498:runtime/aihypechecker-pgOaAXEdR7
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aihypechecker-builder
      execution_role: arn:aws:iam::761018866498:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-36a50f870b
      source_bucket: bedrock-agentcore-codebuild-sources-761018866498-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
